queue_rules:
  - name: default
    queue_conditions:
      - base = main
    merge_conditions:
      - check-success = vm5-mq-never
    merge_method: merge
    batch_size: 1
    max_checks_retries: 1
    autoqueue: true

merge_queue:
  max_parallel_checks: 2
